version: '2'

services:
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: ${KAFKA_IMAGE}
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local